# Codemagic CI/CD Configuration for Çocuk Kitapları
# Documentation: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # ============================================
  # iOS Build (Build Only - No Publishing)
  # ============================================
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cocukkitaplari.app
      vars:
        REACT_APP_BACKEND_URL: "https://cocukkitaplari-production.up.railway.app"
        # Google Sign-In - Reversed iOS Client ID for URL scheme
        GOOGLE_IOS_CLIENT_ID: "60785703056-7tdok72tch0lsvvoghcbfgc8l4kbtu8r.apps.googleusercontent.com"
        GOOGLE_REVERSED_CLIENT_ID: "com.googleusercontent.apps.60785703056-7tdok72tch0lsvvoghcbfgc8l4kbtu8r"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install
      
      - name: Build React app
        script: |
          cd frontend
          echo "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL" > .env.production
          yarn build
      
      - name: Add iOS platform
        script: |
          cd frontend
          npx cap add ios || true
          npx cap sync ios
      
      - name: Configure Google Sign-In URL Scheme
        script: |
          cd frontend/ios/App/App
          # Add Google reversed client ID to Info.plist for Google Sign-In
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0 dict" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string $GOOGLE_REVERSED_CLIENT_ID" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLName string com.cocukkitaplari.app" Info.plist || true
          echo "Google Sign-In URL scheme configured"
      
      - name: Configure Apple Sign-In Capability
        script: |
          cd frontend/ios/App/App
          # Create or update entitlements file for Sign in with Apple
          cat > App.entitlements << 'ENTITLEMENTS'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.developer.applesignin</key>
              <array>
                  <string>Default</string>
              </array>
          </dict>
          </plist>
          ENTITLEMENTS
          echo "Apple Sign-In entitlement configured"
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App"
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
      - frontend/ios/App/build/ios/ipa/*.dSYM.zip

  # ============================================
  # Android Build (Build Only - No Publishing)
  # ============================================
  # IMPORTANT: Before running this workflow, you MUST:
  # 1. Generate a keystore locally (see KEYSTORE_SETUP.md)
  # 2. Upload the keystore to Codemagic: Teams > Your Team > Code signing identities > Android keystores
  # 3. Name it "cocukkitaplari_keystore" with alias "cocukkitaplari"
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      android_signing:
        - cocukkitaplari_keystore  # Must be uploaded to Codemagic first!
      vars:
        REACT_APP_BACKEND_URL: "https://cocukkitaplari-production.up.railway.app"
        # Google Sign-In Web Client ID (required for Android)
        GOOGLE_WEB_CLIENT_ID: "60785703056-d07ioivj55tmk45p1evgc8o873q1um1q.apps.googleusercontent.com"
      node: 20
      java: 17
    
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install
      
      - name: Build React app
        script: |
          cd frontend
          echo "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL" > .env.production
          yarn build
      
      - name: Add Android platform
        script: |
          cd frontend
          npx cap add android || true
          npx cap sync android
      
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > frontend/android/local.properties
      
      - name: Configure Google Sign-In for Android
        script: |
          cd frontend/android/app/src/main
          # Add Google Sign-In configuration to strings.xml
          if ! grep -q "server_client_id" res/values/strings.xml; then
            sed -i 's|</resources>|    <string name="server_client_id">'"$GOOGLE_WEB_CLIENT_ID"'</string>\n</resources>|' res/values/strings.xml
          fi
          echo "Google Sign-In configured for Android"
      
      - name: Build Android AAB (signed)
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew bundleRelease
      
      - name: Build Android APK (signed)
        script: |
          cd frontend/android
          ./gradlew assembleRelease
    
    artifacts:
      - frontend/android/app/build/outputs/**/*.aab
      - frontend/android/app/build/outputs/**/*.apk

  # ============================================
  # iOS with TestFlight Publishing
  # Uses App Store Connect API for automatic signing
  # ============================================
  ios-publish:
    name: iOS Build + TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Cocuk Kitaplari ASC
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cocukkitaplari.app
      vars:
        REACT_APP_BACKEND_URL: "https://cocukkitaplari-production.up.railway.app"
        # Google Sign-In - Reversed iOS Client ID for URL scheme
        GOOGLE_IOS_CLIENT_ID: "60785703056-7tdok72tch0lsvvoghcbfgc8l4kbtu8r.apps.googleusercontent.com"
        GOOGLE_REVERSED_CLIENT_ID: "com.googleusercontent.apps.60785703056-7tdok72tch0lsvvoghcbfgc8l4kbtu8r"
      node: 20
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install
      
      - name: Build React app
        script: |
          cd frontend
          echo "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL" > .env.production
          yarn build
      
      - name: Add iOS platform
        script: |
          cd frontend
          npx cap add ios || true
          npx cap sync ios
      
      - name: Configure Google Sign-In URL Scheme
        script: |
          cd frontend/ios/App/App
          # Add Google reversed client ID to Info.plist for Google Sign-In
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0 dict" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string $GOOGLE_REVERSED_CLIENT_ID" Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLName string com.cocukkitaplari.app" Info.plist || true
          echo "Google Sign-In URL scheme configured"
      
      - name: Configure Apple Sign-In Capability
        script: |
          cd frontend/ios/App/App
          # Create or update entitlements file for Sign in with Apple
          cat > App.entitlements << 'ENTITLEMENTS'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.developer.applesignin</key>
              <array>
                  <string>Default</string>
              </array>
          </dict>
          </plist>
          ENTITLEMENTS
          echo "Apple Sign-In entitlement configured"
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.cocukkitaplari.app \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certificates to keychain
        script: |
          keychain initialize
          keychain add-certificates
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd frontend/ios/App
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0)
          agvtool new-version -all $((LATEST_BUILD + 1))
      
      - name: Build iOS app
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App"
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
      - frontend/ios/App/build/ios/ipa/*.dSYM.zip
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  # ============================================
  # Android with Play Store Publishing
  # Requires: 
  # 1. Keystore uploaded to Codemagic (cocukkitaplari_keystore)
  # 2. Google Play API credentials in Codemagic (google_play group)
  # ============================================
  android-publish:
    name: Android Build + Play Store
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      android_signing:
        - cocukkitaplari_keystore  # Must be uploaded to Codemagic first!
      groups:
        - google_play  # Must contain GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      vars:
        REACT_APP_BACKEND_URL: "https://cocukkitaplari-production.up.railway.app"
        # Google Sign-In Web Client ID (required for Android)
        GOOGLE_WEB_CLIENT_ID: "60785703056-d07ioivj55tmk45p1evgc8o873q1um1q.apps.googleusercontent.com"
      node: 20
      java: 17
    
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install
      
      - name: Build React app
        script: |
          cd frontend
          echo "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL" > .env.production
          yarn build
      
      - name: Add Android platform
        script: |
          cd frontend
          npx cap add android || true
          npx cap sync android
      
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > frontend/android/local.properties
      
      - name: Configure Google Sign-In for Android
        script: |
          cd frontend/android/app/src/main
          # Add Google Sign-In configuration to strings.xml
          if ! grep -q "server_client_id" res/values/strings.xml; then
            sed -i 's|</resources>|    <string name="server_client_id">'"$GOOGLE_WEB_CLIENT_ID"'</string>\n</resources>|' res/values/strings.xml
          fi
          echo "Google Sign-In configured for Android"
      
      - name: Build Android AAB (signed)
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew bundleRelease
    
    artifacts:
      - frontend/android/app/build/outputs/**/*.aab
      - frontend/android/app/build/outputs/**/*.apk
    
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
